server:
  port: 80
spring:
  session:
    store-type: redis
  application:
    name: app-web
#注册中心
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
     serviceUrl:
        defaultZone: http://localhost:9000/eureka
